# Generated by Django 3.1.4 on 2020-12-24 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vias',
            name='imagen',
            field=models.ImageField(upload_to=''),
        ),
    ]
