# Generated by Django 3.1.4 on 2020-12-24 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vias', '0002_auto_20201223_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vias',
            name='imagen',
            field=models.ImageField(null=True, upload_to='ImagenVia'),
        ),
    ]
