# Generated by Django 3.1.4 on 2020-12-19 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vias', '0002_auto_20201219_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipos',
            name='nombre',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
