# Generated by Django 3.1.4 on 2020-12-19 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vias', '0003_auto_20201219_1802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipos',
            old_name='nombre',
            new_name='tipo_via',
        ),
        migrations.RenameField(
            model_name='vias',
            old_name='nombre',
            new_name='nombre_via',
        ),
    ]
