# Generated by Django 3.1.4 on 2020-12-24 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vias', '0003_auto_20201223_2140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vias',
            name='fecha',
        ),
    ]
