# Generated by Django 3.1.4 on 2020-12-20 01:03

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vias', '0004_auto_20201219_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vias',
            name='imagen',
            field=models.ImageField(null=True, upload_to=django.contrib.auth.models.User),
        ),
        migrations.AlterField(
            model_name='vias',
            name='link',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vias',
            name='nombre_via',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
