# Generated by Django 3.1.4 on 2020-12-20 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vias', '0005_auto_20201219_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vias',
            name='imagen',
            field=models.ImageField(null=True, upload_to='Text'),
        ),
    ]
