# Generated by Django 3.1.4 on 2020-12-26 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vias', '0007_auto_20201224_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=20, null=True)),
                ('precio', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='vias',
            name='accion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vias.accion'),
        ),
    ]
