# Generated by Django 3.1.4 on 2020-12-20 01:29

from django.db import migrations, models
import vias.models


class Migration(migrations.Migration):

    dependencies = [
        ('vias', '0007_auto_20201219_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vias',
            name='imagen',
            field=models.ImageField(null=True, upload_to=vias.models.nombre_imagen),
        ),
    ]
