# Generated by Django 3.1.4 on 2020-12-26 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vias', '0008_auto_20201226_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vias',
            name='accion',
        ),
        migrations.AddField(
            model_name='vias',
            name='accion',
            field=models.ManyToManyField(blank=True, null=True, to='vias.Accion'),
        ),
    ]
