# Generated by Django 3.1.4 on 2020-12-20 01:33

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vias', '0008_auto_20201219_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vias',
            name='imagen',
            field=models.ImageField(null=True, upload_to=django.contrib.auth.models.User),
        ),
    ]
