# Generated by Django 3.1.4 on 2020-12-26 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vias', '0009_auto_20201226_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vias',
            name='accion',
            field=models.ManyToManyField(blank=True, to='vias.Accion'),
        ),
    ]
