# Generated by Django 3.1.4 on 2021-01-26 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vias', '0011_accionesyutube'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accionesyutube',
            old_name='Video_ID',
            new_name='Id_Video',
        ),
    ]
