# Generated by Django 3.1.4 on 2021-01-26 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vias', '0013_auto_20210126_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='accionesyutube',
            name='thumbnails',
            field=models.ImageField(null=True, upload_to='ImagenVia'),
        ),
    ]
