# Generated by Django 3.1.4 on 2021-01-26 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vias', '0014_accionesyutube_thumbnails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accionesyutube',
            name='thumbnails',
            field=models.URLField(default=True),
        ),
    ]
