# Generated by Django 3.1.4 on 2021-01-29 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vias', '0016_pasos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pasos',
            new_name='VideoURL',
        ),
        migrations.AddField(
            model_name='accionesyutube',
            name='video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vias.videourl'),
        ),
    ]
