# Generated by Django 3.1.4 on 2021-01-29 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vias', '0018_auto_20210129_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duracion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reproducion', models.BooleanField(default=True)),
                ('Segundos', models.IntegerField(default=25, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='vias',
            name='accion',
        ),
        migrations.RemoveField(
            model_name='vias',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='vias',
            name='usuario',
        ),
        migrations.AlterModelOptions(
            name='accionesyutube',
            options={'verbose_name_plural': 'AccionesYutube'},
        ),
        migrations.RemoveField(
            model_name='accionesyutube',
            name='videoURL',
        ),
        migrations.DeleteModel(
            name='Accion',
        ),
        migrations.DeleteModel(
            name='Tipo',
        ),
        migrations.DeleteModel(
            name='Vias',
        ),
        migrations.DeleteModel(
            name='VideoURL',
        ),
        migrations.AlterField(
            model_name='accionesyutube',
            name='reproducion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vias.duracion'),
        ),
    ]
