# Generated by Django 3.1.4 on 2021-01-29 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vias', '0019_auto_20210129_1344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='duracion',
            old_name='Segundos',
            new_name='segundos',
        ),
        migrations.RemoveField(
            model_name='duracion',
            name='reproducion',
        ),
        migrations.AddField(
            model_name='duracion',
            name='repetir',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
