# Generated by Django 3.1.4 on 2021-01-29 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vias', '0020_auto_20210129_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accionesyutube',
            name='reproducion',
        ),
        migrations.AddField(
            model_name='accionesyutube',
            name='repetir',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='accionesyutube',
            name='segundos',
            field=models.IntegerField(default=25, null=True),
        ),
        migrations.DeleteModel(
            name='Duracion',
        ),
    ]
