# Generated by Django 3.1.4 on 2021-01-09 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0002_auto_20210109_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='foto',
            field=models.ImageField(default='<django.db.models.query_utils.DeferredAttribute object at 0x0000012FACBBDBC8>.png', null=True, upload_to='ImagenVia'),
        ),
    ]
