# Generated by Django 3.1.4 on 2021-01-09 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0003_auto_20210109_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='foto',
            field=models.ImageField(default='<django.db.models.query_utils.DeferredAttribute object at 0x0000026A71CBDC48>.png', null=True, upload_to='ImagenVia'),
        ),
    ]
