# Generated by Django 3.1.4 on 2021-01-25 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0006_auto_20210109_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='foto',
            field=models.ImageField(default='<django.db.models.query_utils.DeferredAttribute object at 0x000002729314F508>.png', null=True, upload_to='ImagenVia'),
        ),
    ]
