# Generated by Django 3.1.4 on 2021-01-27 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0013_auto_20210126_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='foto',
            field=models.ImageField(default='<django.db.models.query_utils.DeferredAttribute object at 0x000002DB2F9DF5C8>.png', null=True, upload_to='ImagenVia'),
        ),
    ]
