# Generated by Django 3.1.4 on 2021-01-29 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0014_auto_20210127_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='foto',
            field=models.ImageField(default='<django.db.models.query_utils.DeferredAttribute object at 0x0000019C670B5948>.png', null=True, upload_to='ImagenVia'),
        ),
    ]
