# Generated by Django 3.1.4 on 2021-01-29 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0016_auto_20210129_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='foto',
            field=models.ImageField(default='<django.db.models.query_utils.DeferredAttribute object at 0x000001DAC6A21888>.png', null=True, upload_to='ImagenVia'),
        ),
    ]
