# Generated by Django 3.1.4 on 2021-01-29 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0020_auto_20210129_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='foto',
            field=models.ImageField(default='<django.db.models.query_utils.DeferredAttribute object at 0x0000019EDC8818C8>.png', null=True, upload_to='ImagenVia'),
        ),
    ]
