# Generated by Django 3.1.4 on 2021-01-29 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0021_auto_20210129_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='foto',
            field=models.ImageField(default='<django.db.models.query_utils.DeferredAttribute object at 0x000002612DD018C8>.png', null=True, upload_to='ImagenVia'),
        ),
    ]
