# Generated by Django 3.1.4 on 2021-01-30 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0022_auto_20210129_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='foto',
            field=models.ImageField(default='<django.db.models.query_utils.DeferredAttribute object at 0x0000023F98D51908>.png', null=True, upload_to='ImagenVia'),
        ),
    ]
