# Generated by Django 3.1.4 on 2021-02-14 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0023_auto_20210130_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='foto',
            field=models.ImageField(default='<django.db.models.query_utils.DeferredAttribute object at 0x0000017CC63B6588>.png', null=True, upload_to='ImagenVia'),
        ),
    ]
