# Generated by Django 3.1.4 on 2021-03-10 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0024_auto_20210213_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='foto',
            field=models.ImageField(default='<django.db.models.query_utils.DeferredAttribute object at 0x000001D49C1F6488>.png', null=True, upload_to='ImagenVia'),
        ),
    ]
